name: Reusable Milestone Creation
on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
        default: 'templates/milestones.json'
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  create-milestones:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Read milestone configuration
        id: milestone-config
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const milestones = JSON.parse(fs.readFileSync('${{ inputs.config-path }}', 'utf8'));
            return milestones;

      - name: Create Milestones
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const milestones = ${{ steps.milestone-config.outputs.result }};
            for (const milestone of milestones) {
              try {
                await github.rest.issues.createMilestone({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: milestone.title,
                  state: milestone.state,
                  description: milestone.description
                });
                console.log(`Created milestone: ${milestone.title}`);
              } catch (error) {
                if (error.status === 422) {
                  console.log(`Milestone ${milestone.title} already exists`);
                } else {
                  throw error;
                }
              }
            }