name: Self Initialize Using Our Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'templates/**'

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  init-self:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Debug File Structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          echo "Action path: ${{ github.action_path }}"
          
      - name: Run Our Own Action
        uses: ./
        with:
          labels-config: '${{ github.workspace }}/templates/labels.json'
          milestones-config: '${{ github.workspace }}/templates/milestones.json'
          token: ${{ secrets.GITHUB_TOKEN }}